# Generated by Django 5.2.3 on 2025-07-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='seen_by_employer',
            field=models.BooleanField(default=False),
        ),
    ]
